name: adella_kitchen
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  google_sign_in: 6.2.1
  ionicons: 0.2.2
  animated_splash_screen: 1.3.0
  cupertino_icons: ^1.0.2
  flutter_signin_button: 2.0.0
  get: 4.6.6
  animated_custom_dropdown: 3.0.0
  icons_plus: 5.0.0
  carousel_slider: 4.2.1
  smooth_page_indicator: 1.1.0
  intl: ^0.18.1
  flutter_launcher_icons: 0.13.1
  badges: ^3.1.2
  input_quantity: 2.3.4
  phone_text_field: 0.0.7
  pinput: 4.0.0
  flutter_secure_storage: ^8.1.0
  fancy_shimmer_image: 2.0.3
  path_provider: 2.1.3
  flutter_cache_manager: 3.3.2

dev_dependencies: 
  get_cli: ^1.8.1
  flutter_lints: ^3.0.2
  flutter: 
    sdk: flutter
  flutter_test: 
    sdk: flutter

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/img/icon_launcher.png
  flutter: 
    sdk: flutter
  ios: true

flutter: 
  assets: 
    - assets/img/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
  uses-material-design: true

