name: adella_kitchen
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  animated_splash_screen: any
  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar: ^5.0.2
  another_flutter_splash_screen: ^1.2.0
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/img/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
  uses-material-design: true

